# Site Settings
lang: en
title: Rocket CDS
tagline: Rocket CDS
#email: 

#favicon: /path/to/favicon.png
permalink: pretty

remote_theme: chrisrhymes/bulma-clean-theme

show_sidebar: true
#menubar: docs_menu

